# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 12:32
from __future__ import unicode_literals

import colorfield.fields
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_group_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'affected_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'alert_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GCA_NGCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_area', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gca_ngca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oblast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oblast_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'oblasts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_name', models.CharField(max_length=120)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'settlements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_referal', models.DateField(verbose_name='Date of Incident')),
                ('informant', models.TextField(blank=True, null=True)),
                ('conflict_related', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('description', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('source_info', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('date_update', models.DateField(blank=True, null=True)),
                ('uncovered_needs', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info_link', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True, verbose_name='Baseline population')),
                ('population_males', models.BigIntegerField(blank=True, null=True)),
                ('population_females', models.BigIntegerField(blank=True, null=True)),
                ('population_children', models.BigIntegerField(blank=True, null=True)),
                ('population_adult', models.BigIntegerField(blank=True, null=True)),
                ('population_elderly', models.BigIntegerField(blank=True, null=True)),
                ('no_affected', models.IntegerField(verbose_name='Number of affected (ind.)')),
                ('no_affected_males', models.BigIntegerField(blank=True, null=True)),
                ('no_affected_females', models.BigIntegerField(blank=True, null=True)),
                ('no_affected_children', models.BigIntegerField(blank=True, null=True)),
                ('no_affected_adult', models.BigIntegerField(blank=True, null=True)),
                ('no_affected_elderly', models.BigIntegerField(blank=True, null=True)),
                ('no_beneficiaries', models.IntegerField(blank=True, null=True, verbose_name='Number of beneficiaries')),
                ('no_beneficiaries_males', models.BigIntegerField(blank=True, null=True)),
                ('no_beneficiaries_females', models.BigIntegerField(blank=True, null=True)),
                ('no_beneficiaries_children', models.BigIntegerField(blank=True, null=True)),
                ('no_beneficiaries_adult', models.BigIntegerField(blank=True, null=True)),
                ('no_beneficiaries_elderly', models.BigIntegerField(blank=True, null=True)),
                ('gap_beneficiaries', models.IntegerField(blank=True, null=True)),
                ('gap_beneficiaries_males', models.BigIntegerField(blank=True, null=True)),
                ('gap_beneficiaries_females', models.BigIntegerField(blank=True, null=True)),
                ('gap_beneficiaries_children', models.BigIntegerField(blank=True, null=True)),
                ('gap_beneficiaries_adult', models.BigIntegerField(blank=True, null=True)),
                ('gap_beneficiaries_elderly', models.BigIntegerField(blank=True, null=True)),
                ('affected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_id', to='AlertsMap.AffectedGroup', verbose_name='Affected group')),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.AlertType')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='AlertItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_details', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Alert')),
            ],
            options={
                'db_table': 'alert_items',
            },
        ),
        migrations.CreateModel(
            name='BaselinePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_total', models.IntegerField(blank=True, null=True)),
                ('population_males', models.IntegerField(blank=True, null=True)),
                ('population_females', models.IntegerField(blank=True, null=True)),
                ('population_adult', models.IntegerField(blank=True, null=True)),
                ('population_children', models.IntegerField(blank=True, null=True)),
                ('population_elderly', models.IntegerField(blank=True, null=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Alert')),
            ],
            options={
                'db_table': 'baseline_population',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'clusters',
            },
        ),
        migrations.CreateModel(
            name='ConfirmationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'confirmation_status',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=80, null=True)),
                ('item_label_en', models.CharField(blank=True, max_length=120, null=True)),
                ('item_label_ua', models.CharField(blank=True, max_length=120, null=True)),
                ('item_label_ru', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'item_groups',
            },
        ),
        migrations.CreateModel(
            name='NeedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'need_types',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=80)),
                ('organization_acronym', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80, null=True)),
            ],
            options={
                'db_table': 'organization_types',
            },
        ),
        migrations.CreateModel(
            name='Raion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raion_name', models.CharField(max_length=100)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=10)),
                ('oblast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Oblast')),
            ],
            options={
                'db_table': 'raions',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_details', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Alert')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Item')),
                ('response_partners', models.ManyToManyField(related_name='response_partners_id', to='AlertsMap.Organization')),
            ],
            options={
                'db_table': 'responses',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=15, null=True)),
                ('unit_label_en', models.CharField(blank=True, max_length=30, null=True)),
                ('unit_label_ua', models.CharField(blank=True, max_length=30, null=True)),
                ('unit_label_ru', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'item_units',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('organization', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Unit'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.OrganizationType'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.ItemGroup'),
        ),
        migrations.AddField(
            model_name='alertitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Item'),
        ),
        migrations.AddField(
            model_name='alertitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Unit'),
        ),
        migrations.AddField(
            model_name='alert',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Cluster', verbose_name='Primary cluster'),
        ),
        migrations.AddField(
            model_name='alert',
            name='clusters',
            field=models.ManyToManyField(related_name='clusters_id', to='AlertsMap.Cluster'),
        ),
        migrations.AddField(
            model_name='alert',
            name='confirmation_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.ConfirmationStatus'),
        ),
        migrations.AddField(
            model_name='alert',
            name='gca_ngca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.GCA_NGCA', verbose_name='GCA/NGCA'),
        ),
        migrations.AddField(
            model_name='alert',
            name='need_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.NeedType', verbose_name='Primary need type'),
        ),
        migrations.AddField(
            model_name='alert',
            name='need_types',
            field=models.ManyToManyField(related_name='need_types_id', to='AlertsMap.NeedType'),
        ),
        migrations.AddField(
            model_name='alert',
            name='oblast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Oblast'),
        ),
        migrations.AddField(
            model_name='alert',
            name='raion',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='oblast', chained_model_field='oblast', on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Raion'),
        ),
        migrations.AddField(
            model_name='alert',
            name='referral_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_agency_id', to='AlertsMap.Organization'),
        ),
        migrations.AddField(
            model_name='alert',
            name='response_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_partner_id', to='AlertsMap.Organization', verbose_name='Primary response partner'),
        ),
        migrations.AddField(
            model_name='alert',
            name='settlement',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='raion', chained_model_field='raion', on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Settlement'),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Status'),
        ),
    ]
