# Generated by Django 2.2.7 on 2019-11-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinationhub',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coordinationhub',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coordinationhub',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
