# Generated by Django 2.2.8 on 2020-01-15 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0003_auto_20191128_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='affected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_id', to='AlertsMap.AffectedGroup', verbose_name='Affected Group'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.AlertType', verbose_name='Alert Type'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='clusters',
            field=models.ManyToManyField(related_name='clusters_id', to='AlertsMap.Cluster', verbose_name='Clusters'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='confirmation_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.ConfirmationStatus', verbose_name='Confirmation Status'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='conflict_related',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], verbose_name='Conflict related'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='context_en',
            field=models.TextField(blank=True, null=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='context_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='context_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='date_update',
            field=models.DateField(blank=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='informant',
            field=models.TextField(blank=True, null=True, verbose_name='Informant'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='informant_en',
            field=models.TextField(blank=True, null=True, verbose_name='Informant'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='informant_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Informant'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='informant_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Informant'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='need_types',
            field=models.ManyToManyField(related_name='needs', to='AlertsMap.NeedType', verbose_name='Need Types'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='no_affected_adult',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of affected (adult)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='no_affected_children',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of affected (children)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='no_affected_elderly',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of affected (elderly)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='no_affected_females',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of affected (female)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='no_affected_males',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of affected (male)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='no_beneficiaries_adult',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of affected (ind.)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='no_beneficiaries_children',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of affected (ind.)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='no_beneficiaries_elderly',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of affected (ind.)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='no_beneficiaries_females',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of affected (ind.)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='no_beneficiaries_males',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of affected (ind.)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='oblast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Oblast', verbose_name='Oblast'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='raion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Raion', verbose_name='Raion'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Settlement', verbose_name='Settlement'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='pcode',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
