# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0003_auto_20170222_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baselinepopulation',
            name='alert',
        ),
        migrations.AlterField(
            model_name='response',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='AlertsMap.Alert'),
        ),
        migrations.DeleteModel(
            name='BaselinePopulation',
        ),
    ]
