# Generated by Django 2.2.8 on 2020-01-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0004_auto_20200115_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertitem',
            name='item_details_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='alertitem',
            name='item_details_ru',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='alertitem',
            name='item_details_uk',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
