# Generated by Django 2.2.8 on 2020-01-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0005_auto_20200115_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_acronym_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_acronym_ru',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_acronym_uk',
        ),
    ]
