# Generated by Django 2.2.8 on 2020-01-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0006_auto_20200115_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'mail_config',
            },
        ),
    ]
