# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0006_remove_response_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='additional_info_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='alert_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.AlertType'),
        ),
        migrations.AddField(
            model_name='album',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Cluster', verbose_name='Primary cluster'),
        ),
        migrations.AddField(
            model_name='album',
            name='clusters',
            field=models.ManyToManyField(blank=True, null=True, related_name='album_clusters', to='AlertsMap.Cluster'),
        ),
        migrations.AddField(
            model_name='album',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='confirmation_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.ConfirmationStatus'),
        ),
        migrations.AddField(
            model_name='album',
            name='conflict_related',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='date_referal',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Incident'),
        ),
        migrations.AddField(
            model_name='album',
            name='date_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='gap_beneficiaries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='gap_beneficiaries_adult',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='gap_beneficiaries_children',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='gap_beneficiaries_elderly',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='gap_beneficiaries_females',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='gap_beneficiaries_males',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='gca_ngca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.GCA_NGCA', verbose_name='GCA/NGCA'),
        ),
        migrations.AddField(
            model_name='album',
            name='informant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='need_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.NeedType', verbose_name='Primary need type'),
        ),
        migrations.AddField(
            model_name='album',
            name='need_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='album_need_types', to='AlertsMap.NeedType'),
        ),
        migrations.AddField(
            model_name='album',
            name='no_affected',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of affected (ind.)'),
        ),
        migrations.AddField(
            model_name='album',
            name='no_affected_adult',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='no_affected_children',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='no_affected_elderly',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='no_affected_females',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='no_affected_males',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='no_beneficiaries',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of beneficiaries'),
        ),
        migrations.AddField(
            model_name='album',
            name='no_beneficiaries_adult',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='no_beneficiaries_children',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='no_beneficiaries_elderly',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='no_beneficiaries_females',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='no_beneficiaries_males',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='oblast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Oblast'),
        ),
        migrations.AddField(
            model_name='album',
            name='population',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Baseline population'),
        ),
        migrations.AddField(
            model_name='album',
            name='population_adult',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='population_children',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='population_elderly',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='population_females',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='population_males',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='raion',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='oblast', chained_model_field='oblast', null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Raion'),
        ),
        migrations.AddField(
            model_name='album',
            name='referral_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_referral_agency', to='AlertsMap.Organization'),
        ),
        migrations.AddField(
            model_name='album',
            name='response_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_response_partner', to='AlertsMap.Organization', verbose_name='Primary response partner'),
        ),
        migrations.AddField(
            model_name='album',
            name='settlement',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='raion', chained_model_field='raion', null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Settlement'),
        ),
        migrations.AddField(
            model_name='album',
            name='source_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Status'),
        ),
        migrations.AddField(
            model_name='album',
            name='uncovered_needs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
