# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0007_auto_20170222_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='clusters',
            field=models.ManyToManyField(related_name='album_clusters', to='AlertsMap.Cluster'),
        ),
        migrations.AlterField(
            model_name='album',
            name='need_types',
            field=models.ManyToManyField(related_name='album_need_types', to='AlertsMap.NeedType'),
        ),
    ]
