# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0008_auto_20170223_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='album',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='album',
            name='clusters',
        ),
        migrations.RemoveField(
            model_name='album',
            name='confirmation_status',
        ),
        migrations.RemoveField(
            model_name='album',
            name='gca_ngca',
        ),
        migrations.RemoveField(
            model_name='album',
            name='need_type',
        ),
        migrations.RemoveField(
            model_name='album',
            name='need_types',
        ),
        migrations.RemoveField(
            model_name='album',
            name='oblast',
        ),
        migrations.RemoveField(
            model_name='album',
            name='raion',
        ),
        migrations.RemoveField(
            model_name='album',
            name='referral_agency',
        ),
        migrations.RemoveField(
            model_name='album',
            name='response_partner',
        ),
        migrations.RemoveField(
            model_name='album',
            name='settlement',
        ),
        migrations.RemoveField(
            model_name='album',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AddField(
            model_name='response',
            name='response_partners',
            field=models.ManyToManyField(related_name='response_partners_id', to='AlertsMap.Organization'),
        ),
        migrations.AddField(
            model_name='response',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Unit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
