# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0009_auto_20170223_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='need_type',
        ),
        migrations.AlterField(
            model_name='alert',
            name='need_types',
            field=models.ManyToManyField(related_name='needs', to='AlertsMap.NeedType'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='response_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_partner_id', to='AlertsMap.Organization', verbose_name='Primary response partner'),
        ),
    ]
