# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-24 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0011_auto_20170223_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='action',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='uncovered_needs',
        ),
        migrations.AddField(
            model_name='response',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='uncovered_needs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
