# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-24 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0012_auto_20170224_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
