# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0013_response_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['organization_name']},
        ),
    ]
