# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0014_auto_20170227_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertitem',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AlertsMap.Alert'),
        ),
        migrations.AlterField(
            model_name='alertitem',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
