# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0015_auto_20170309_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
