# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0017_raion_pcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oblast',
            options={},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={},
        ),
    ]
