# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0018_auto_20170314_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='raion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Raion'),
            preserve_default=False,
        ),
    ]
