# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0019_auto_20170314_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='oblast',
            name='pcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.GCA_NGCA'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='pcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
