# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0020_auto_20170314_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinationHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='settlement',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.CoordinationHub'),
        ),
    ]
