# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0021_auto_20170314_1303'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coordinationhub',
            table='coordination_hubs',
        ),
    ]
