# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0022_auto_20170314_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='pcode_new',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_name_old',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
