# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0023_auto_20170314_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'emails',
            },
        ),
        migrations.AddField(
            model_name='coordinationhub',
            name='cc_list',
            field=models.ManyToManyField(related_name='cc_emails', to='AlertsMap.Emails'),
        ),
        migrations.AddField(
            model_name='coordinationhub',
            name='to_list',
            field=models.ManyToManyField(related_name='to_emails', to='AlertsMap.Emails'),
        ),
    ]
