# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0024_auto_20170314_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinationhub',
            name='cc_list',
        ),
        migrations.RemoveField(
            model_name='coordinationhub',
            name='to_list',
        ),
        migrations.AddField(
            model_name='emails',
            name='cc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cc_emails', to='AlertsMap.CoordinationHub'),
        ),
        migrations.AddField(
            model_name='emails',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_emails', to='AlertsMap.CoordinationHub'),
        ),
    ]
