# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0025_auto_20170314_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailsCc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'emails_cc',
            },
        ),
        migrations.CreateModel(
            name='EmailsTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'emails_to',
            },
        ),
        migrations.RemoveField(
            model_name='emails',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='emails',
            name='to',
        ),
        migrations.AddField(
            model_name='emailsto',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Emails'),
        ),
        migrations.AddField(
            model_name='emailsto',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.CoordinationHub'),
        ),
        migrations.AddField(
            model_name='emailscc',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Emails'),
        ),
        migrations.AddField(
            model_name='emailscc',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.CoordinationHub'),
        ),
    ]
