# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0026_auto_20170314_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailscc',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailscc',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='emailsto',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailsto',
            name='hub',
        ),
        migrations.AddField(
            model_name='coordinationhub',
            name='cc_list',
            field=models.ManyToManyField(related_name='cc_emails', to='AlertsMap.Emails'),
        ),
        migrations.AddField(
            model_name='coordinationhub',
            name='to_list',
            field=models.ManyToManyField(related_name='to_emails', to='AlertsMap.Emails'),
        ),
        migrations.DeleteModel(
            name='EmailsCc',
        ),
        migrations.DeleteModel(
            name='EmailsTo',
        ),
    ]
