# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-01 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0027_auto_20170315_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name_plural': 'Emails'},
        ),
        migrations.AddField(
            model_name='cluster',
            name='cc_list',
            field=models.ManyToManyField(related_name='cc_emails_cluster', to='AlertsMap.Emails'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='to_list',
            field=models.ManyToManyField(related_name='to_emails_cluster', to='AlertsMap.Emails'),
        ),
    ]
