# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-22 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0028_auto_20170801_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_list', models.ManyToManyField(related_name='cc_emails', to='AlertsMap.Emails')),
            ],
            options={
                'db_table': 'cluster_emails',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clusteremail',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.Cluster'),
        ),
        migrations.AddField(
            model_name='clusteremail',
            name='coordination_hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlertsMap.CoordinationHub'),
        ),
        migrations.AddField(
            model_name='clusteremail',
            name='to_list',
            field=models.ManyToManyField(related_name='to_emails', to='AlertsMap.Emails'),
        ),
    ]
