# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0030_auto_20170823_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='cc_list',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='to_list',
        )
    ]
