# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-01 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0031_auto_20170823_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_label_en',
            new_name='item_name_en',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_label_ru',
            new_name='item_name_ru',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_label_ua',
            new_name='item_name_uk',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unit_label_en',
            new_name='unit_name_en',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unit_label_ru',
            new_name='unit_name_ru',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unit_label_ua',
            new_name='unit_name_uk',
        ),
        migrations.AddField(
            model_name='cluster',
            name='cluster_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='cluster_name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='cluster_name_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='confirmationstatus',
            name='confirmation_status_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='confirmationstatus',
            name='confirmation_status_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='confirmationstatus',
            name='confirmation_status_uk',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='needtype',
            name='need_type_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='needtype',
            name='need_type_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='needtype',
            name='need_type_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oblast',
            name='oblast_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oblast',
            name='oblast_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oblast',
            name='oblast_name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_acronym_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_acronym_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_acronym_uk',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name_uk',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='type_uk',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='raion',
            name='raion_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='raion',
            name='raion_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='raion',
            name='raion_name_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_name_uk',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
