# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-25 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlertsMap', '0032_auto_20170901_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectedgroup',
            options={'managed': False, 'verbose_name': 'Affected Group', 'verbose_name_plural': 'Affected Groups'},
        ),
        migrations.AlterModelOptions(
            name='alerttype',
            options={'managed': False, 'verbose_name': 'Alert Type', 'verbose_name_plural': 'Alert Types'},
        ),
        migrations.AlterModelOptions(
            name='cluster',
            options={'verbose_name': 'Cluster', 'verbose_name_plural': 'Clusters'},
        ),
        migrations.AlterModelOptions(
            name='coordinationhub',
            options={'verbose_name': 'Coordination hub', 'verbose_name_plural': 'Coordination hubs'},
        ),
        migrations.AlterModelOptions(
            name='emails',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
        migrations.AlterModelOptions(
            name='needtype',
            options={'verbose_name': 'Need Type', 'verbose_name_plural': 'Need Types'},
        ),
        migrations.AlterModelOptions(
            name='oblast',
            options={'verbose_name': 'Oblast', 'verbose_name_plural': 'Oblasts'},
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='raion',
            options={'verbose_name': 'Raion', 'verbose_name_plural': 'Raions'},
        ),
        migrations.AlterModelOptions(
            name='settlement',
            options={'verbose_name': 'Settlement', 'verbose_name_plural': 'Settlements'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'managed': False, 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(max_length=80, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name_uk',
            field=models.CharField(max_length=80, null=True, verbose_name='Organization Name'),
        ),
    ]
